#!/usr/bin/python -i
import sys
import main
url = None
user = None
if len(sys.argv) > 1:
    url = sys.argv[1]
if len(sys.argv) > 2:
    user = sys.argv[2]
if url:
    p = main.connect(url=url, user=user)
else:
    p = main.connect(user=user)
