FROM frolvlad/alpine-python2

# COPY ALL
COPY adhoc-server /
COPY RPCC /
RUN apk add mariadb-dev build-base python2 python2-dev sed

# https://github.com/DefectDojo/django-DefectDojo/issues/407#issuecomment-415862064
RUN sed '/st_mysql_options options;/a unsigned int reconnect;' /usr/include/mysql/mysql.h -i.bkp
RUN pip install enum34 mysql-python mysql-connector-python

